/**
 * Core modules shared between all run modes.
 */

export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type PromptOptions,
	type SessionStats,
} from "./agent-session.ts";
export {
	AgentSessionRuntime,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	createAgentSessionRuntime,
} from "./agent-session-runtime.ts";
export {
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionServicesOptions,
	createAgentSessionFromServices,
	createAgentSessionServices,
} from "./agent-session-services.ts";
export { type BashExecutorOptions, type BashResult, executeBashWithOperations } from "./bash-executor.ts";
export type { CompactionResult } from "./compaction/index.ts";
export {
	createDiscordHeartbeatEvent,
	createDiscordJsTransportClient,
	createDiscordSessionEnvelope,
	createDiscordTransport,
	type DiscordActionPlan,
	type DiscordActionType,
	type DiscordClientIdentity,
	type DiscordDirective,
	type DiscordDirectiveType,
	type DiscordInboundEvent,
	type DiscordInboundEventType,
	type DiscordSessionEnvelope,
	type DiscordTransport,
	type DiscordTransportClientAdapter,
	type DiscordTransportConfig,
	type DiscordTransportDefaults,
	type DiscordTransportMessageLike,
	type DiscordTransportReactionLike,
	type DiscordTransportSessionLike,
	type DiscordTransportState,
	getDiscordTransportDefaults,
	normalizeDiscordMessage,
	normalizeDiscordReaction,
	normalizeDiscordReadyEvent,
	parseDiscordDirective,
	planDiscordActions,
	type ResolvedDiscordTransportConfig,
	resolveDiscordToken,
	resolveDiscordTransportConfig,
} from "./discord-transport.ts";
export { createEventBus, type EventBus, type EventBusController } from "./event-bus.ts";
// Extensions system
export {
	type AgentEndEvent,
	type AgentStartEvent,
	type AgentToolResult,
	type AgentToolUpdateCallback,
	type BeforeAgentStartEvent,
	type BeforeAgentStartEventResult,
	type BuildSystemPromptOptions,
	type ContextEvent,
	defineTool,
	discoverAndLoadExtensions,
	type ExecOptions,
	type ExecResult,
	type Extension,
	type ExtensionAPI,
	type ExtensionCommandContext,
	type ExtensionContext,
	type ExtensionError,
	type ExtensionEvent,
	type ExtensionFactory,
	type ExtensionFlag,
	type ExtensionHandler,
	ExtensionRunner,
	type ExtensionShortcut,
	type ExtensionUIContext,
	type LoadExtensionsResult,
	type MessageRenderer,
	type RegisteredCommand,
	type SessionBeforeCompactEvent,
	type SessionBeforeForkEvent,
	type SessionBeforeSwitchEvent,
	type SessionBeforeTreeEvent,
	type SessionCompactEvent,
	type SessionShutdownEvent,
	type SessionStartEvent,
	type SessionTreeEvent,
	type ToolCallEvent,
	type ToolCallEventResult,
	type ToolDefinition,
	type ToolRenderResultOptions,
	type ToolResultEvent,
	type TurnEndEvent,
	type TurnStartEvent,
	type WorkingIndicatorOptions,
} from "./extensions/index.ts";
export {
	createSessionArchiveRuntime,
	PiArchiveEnforcement,
	type PiArchiveEvent,
	PiArchiveWriter,
	type PiSessionEnvelope,
	type ResolvedSessionArchiveConfig,
	resolveSessionArchiveConfig,
	type SessionArchiveConfig,
	SessionArchiveDefaults,
	type SessionArchiveEventType,
	type SessionArchiveRedactMode,
	type SessionArchiveRole,
	type SessionArchiveRuntime,
} from "./session-archive.ts";
export { createSyntheticSourceInfo } from "./source-info.ts";
